/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.FacadeDB;
import Product.Computer;
import Product.ProductFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Computers extends javax.swing.JFrame {

    /**
     * Creates new form Computers
     */
    private final String TYPE = "Computer";
    FacadeDB db;

    public Computers() {
        initComponents();
        try {
            db = new FacadeDB();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Computers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jprice = new javax.swing.JTextField();
        Jversion = new javax.swing.JTextField();
        Jhhd = new javax.swing.JTextField();
        Jvideocard = new javax.swing.JTextField();
        Jadd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Jtype = new javax.swing.JTextField();
        Jcancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Jid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Price");

        jLabel3.setText("Version");

        jLabel4.setText("HHD");

        jLabel5.setText("Video Card");

        Jprice.setText(" ");

        Jversion.setText(" ");
        Jversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JversionActionPerformed(evt);
            }
        });

        Jhhd.setText(" ");

        Jvideocard.setText(" ");

        Jadd.setText("Add");
        Jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JaddActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        Jtype.setText(" ");
        Jtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtypeActionPerformed(evt);
            }
        });

        Jcancel.setText("Cancel");
        Jcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcancelActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        Jid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jtype)
                                .addComponent(Jprice)
                                .addComponent(Jversion)
                                .addComponent(Jid)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jhhd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Jvideocard, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Jadd)
                        .addGap(18, 18, 18)
                        .addComponent(Jcancel)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Jprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Jversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Jhhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Jvideocard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jadd)
                    .addComponent(Jcancel))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtypeActionPerformed

    }//GEN-LAST:event_JtypeActionPerformed

    private void JidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JidActionPerformed

    private void JaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JaddActionPerformed

        try {
            db.addComputer(getComputerData());
            JOptionPane.showMessageDialog(null, "Correct!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Invalid!");

        }


    }//GEN-LAST:event_JaddActionPerformed

    private void JversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JversionActionPerformed

    private void JcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcancelActionPerformed

        this.setVisible(false);


    }//GEN-LAST:event_JcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Computers().setVisible(true);
            }
        });
    }

    public Computer getComputerData() {

        String price = Jprice.getText();
        String version = Jversion.getText();
        String hhd = this.getJhhd().getText();
        String type = Jtype.getText();
        String videocard = Jvideocard.getText();
        String id = this.getJid().getText();

        Computer computer = (Computer) ProductFactory.getProduct(TYPE);

        computer.setNo(id);
        computer.setVersion(version);
        computer.setHHD(hhd);
        computer.setType(type);
        computer.setVideoCard(videocard);
        computer.setPrice(price);

        return computer;
    }

    public JTextField getJhhd() {
        return Jhhd;
    }

    public JTextField getJid() {
        return Jid;
    }

    public JTextField getJprice() {
        return Jprice;
    }

    public JTextField getJtype() {
        return Jtype;
    }

    public JTextField getJversion() {
        return Jversion;
    }

    public JTextField getJvideocard() {
        return Jvideocard;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jadd;
    private javax.swing.JButton Jcancel;
    private javax.swing.JTextField Jhhd;
    private javax.swing.JTextField Jid;
    private javax.swing.JTextField Jprice;
    private javax.swing.JTextField Jtype;
    private javax.swing.JTextField Jversion;
    private javax.swing.JTextField Jvideocard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
